import { CONTRACTOR_REGISTRATION } from "./actionTypes/ta-actionTypes";

export const contractorRegistration = (
  step,
  firstName,
  lastName,
  actualSsn,
  maskedSsn,
  ssnLocked,
  service,
  email,
  image,
  url,
  progress,
  name,
  address,
  city,
  state,
  zipCode,
  largeItems,
  selectedDate,
  selectedTime,
  flightOfStairs,
  truckLoads,
  typeOfTruck,
  specialInstructions,
  budget
) => {
  return {
    type: CONTRACTOR_REGISTRATION,
    step,
    firstName,
    lastName,
    actualSsn,
    maskedSsn,
    ssnLocked,
    service,
    email,
    image,
    url,
    progress,
    name,
    address,
    city,
    state,
    zipCode,
    largeItems,
    selectedDate,
    selectedTime,
    flightOfStairs,
    truckLoads,
    typeOfTruck,
    specialInstructions,
    budget
  };
};
